// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "server/server.proto" (package "server", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Server } from "./server";
import type { Any } from "../google/protobuf/any";
import type { UnsubscribeRequest } from "./server";
import type { SubscribeResponse } from "./server";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CallResponse } from "./server";
import type { Request } from "./server";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service server.Server
 */
export interface IServerClient {
    /**
     * @generated from protobuf rpc: Call(server.Request) returns (server.CallResponse);
     */
    call(input: Request, options?: RpcOptions): UnaryCall<Request, CallResponse>;
    /**
     * @generated from protobuf rpc: Subscribe(server.Request) returns (server.SubscribeResponse);
     */
    subscribe(input: Request, options?: RpcOptions): UnaryCall<Request, SubscribeResponse>;
    /**
     * @generated from protobuf rpc: UnSubscribe(server.UnsubscribeRequest) returns (google.protobuf.Any);
     */
    unSubscribe(input: UnsubscribeRequest, options?: RpcOptions): UnaryCall<UnsubscribeRequest, Any>;
}
/**
 * @generated from protobuf service server.Server
 */
export class ServerClient implements IServerClient, ServiceInfo {
    typeName = Server.typeName;
    methods = Server.methods;
    options = Server.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Call(server.Request) returns (server.CallResponse);
     */
    call(input: Request, options?: RpcOptions): UnaryCall<Request, CallResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Request, CallResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Subscribe(server.Request) returns (server.SubscribeResponse);
     */
    subscribe(input: Request, options?: RpcOptions): UnaryCall<Request, SubscribeResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Request, SubscribeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnSubscribe(server.UnsubscribeRequest) returns (google.protobuf.Any);
     */
    unSubscribe(input: UnsubscribeRequest, options?: RpcOptions): UnaryCall<UnsubscribeRequest, Any> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnsubscribeRequest, Any>("unary", this._transport, method, opt, input);
    }
}
