// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "gsm/gsm.proto" (package "gsm", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Gsm } from "./gsm";
import type { FlashCallBackRequest } from "./gsm";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Response } from "../common/common";
import type { FlashCallRequest } from "./gsm";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service gsm.Gsm
 */
export interface IGsmClient {
    /**
     *  rpc SendSms(SendSmsRequest) returns(common.Response);
     *
     * @generated from protobuf rpc: FlashCall(gsm.FlashCallRequest) returns (common.Response);
     */
    flashCall(input: FlashCallRequest, options?: RpcOptions): UnaryCall<FlashCallRequest, Response>;
    /**
     * @generated from protobuf rpc: FlashCallBack(gsm.FlashCallBackRequest) returns (common.Response);
     */
    flashCallBack(input: FlashCallBackRequest, options?: RpcOptions): UnaryCall<FlashCallBackRequest, Response>;
}
/**
 * @generated from protobuf service gsm.Gsm
 */
export class GsmClient implements IGsmClient, ServiceInfo {
    typeName = Gsm.typeName;
    methods = Gsm.methods;
    options = Gsm.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     *  rpc SendSms(SendSmsRequest) returns(common.Response);
     *
     * @generated from protobuf rpc: FlashCall(gsm.FlashCallRequest) returns (common.Response);
     */
    flashCall(input: FlashCallRequest, options?: RpcOptions): UnaryCall<FlashCallRequest, Response> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<FlashCallRequest, Response>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FlashCallBack(gsm.FlashCallBackRequest) returns (common.Response);
     */
    flashCallBack(input: FlashCallBackRequest, options?: RpcOptions): UnaryCall<FlashCallBackRequest, Response> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<FlashCallBackRequest, Response>("unary", this._transport, method, opt, input);
    }
}
