// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "users/users.proto" (package "users", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Users } from "./users";
import type { RemovePhoneRequest } from "./users";
import type { AddPhoneRequest } from "./users";
import type { UpdatePhotoRequest } from "./users";
import type { UpdatePasswordRequest } from "./users";
import type { UpdateAccountDataRequest } from "./users";
import type { Account } from "./users";
import type { CommonRequest } from "./users";
import type { HasSessionRequest } from "./users";
import type { LoginResponse } from "./users";
import type { LoginRequest } from "./users";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CommonResponse } from "./users";
import type { RegisterRequest } from "./users";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service users.Users
 */
export interface IUsersClient {
    /**
     * @generated from protobuf rpc: Register(users.RegisterRequest) returns (users.CommonResponse);
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: Login(users.LoginRequest) returns (users.LoginResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: HasSession(users.HasSessionRequest) returns (users.CommonResponse);
     */
    hasSession(input: HasSessionRequest, options?: RpcOptions): UnaryCall<HasSessionRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: GetAccount(users.CommonRequest) returns (users.Account);
     */
    getAccount(input: CommonRequest, options?: RpcOptions): UnaryCall<CommonRequest, Account>;
    /**
     * @generated from protobuf rpc: UpdateAccountData(users.UpdateAccountDataRequest) returns (users.CommonResponse);
     */
    updateAccountData(input: UpdateAccountDataRequest, options?: RpcOptions): UnaryCall<UpdateAccountDataRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: UpdatePassword(users.UpdatePasswordRequest) returns (users.CommonResponse);
     */
    updatePassword(input: UpdatePasswordRequest, options?: RpcOptions): UnaryCall<UpdatePasswordRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: UpdatePhoto(users.UpdatePhotoRequest) returns (users.CommonResponse);
     */
    updatePhoto(input: UpdatePhotoRequest, options?: RpcOptions): UnaryCall<UpdatePhotoRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: AddPhone(users.AddPhoneRequest) returns (users.CommonResponse);
     */
    addPhone(input: AddPhoneRequest, options?: RpcOptions): UnaryCall<AddPhoneRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: UpdatePhone(users.UpdatePhotoRequest) returns (users.CommonResponse);
     */
    updatePhone(input: UpdatePhotoRequest, options?: RpcOptions): UnaryCall<UpdatePhotoRequest, CommonResponse>;
    /**
     * @generated from protobuf rpc: RemovePhone(users.RemovePhoneRequest) returns (users.CommonResponse);
     */
    removePhone(input: RemovePhoneRequest, options?: RpcOptions): UnaryCall<RemovePhoneRequest, CommonResponse>;
}
/**
 * @generated from protobuf service users.Users
 */
export class UsersClient implements IUsersClient, ServiceInfo {
    typeName = Users.typeName;
    methods = Users.methods;
    options = Users.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Register(users.RegisterRequest) returns (users.CommonResponse);
     */
    register(input: RegisterRequest, options?: RpcOptions): UnaryCall<RegisterRequest, CommonResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Login(users.LoginRequest) returns (users.LoginResponse);
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: HasSession(users.HasSessionRequest) returns (users.CommonResponse);
     */
    hasSession(input: HasSessionRequest, options?: RpcOptions): UnaryCall<HasSessionRequest, CommonResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<HasSessionRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAccount(users.CommonRequest) returns (users.Account);
     */
    getAccount(input: CommonRequest, options?: RpcOptions): UnaryCall<CommonRequest, Account> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CommonRequest, Account>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAccountData(users.UpdateAccountDataRequest) returns (users.CommonResponse);
     */
    updateAccountData(input: UpdateAccountDataRequest, options?: RpcOptions): UnaryCall<UpdateAccountDataRequest, CommonResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateAccountDataRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePassword(users.UpdatePasswordRequest) returns (users.CommonResponse);
     */
    updatePassword(input: UpdatePasswordRequest, options?: RpcOptions): UnaryCall<UpdatePasswordRequest, CommonResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePasswordRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePhoto(users.UpdatePhotoRequest) returns (users.CommonResponse);
     */
    updatePhoto(input: UpdatePhotoRequest, options?: RpcOptions): UnaryCall<UpdatePhotoRequest, CommonResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePhotoRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddPhone(users.AddPhoneRequest) returns (users.CommonResponse);
     */
    addPhone(input: AddPhoneRequest, options?: RpcOptions): UnaryCall<AddPhoneRequest, CommonResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddPhoneRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePhone(users.UpdatePhotoRequest) returns (users.CommonResponse);
     */
    updatePhone(input: UpdatePhotoRequest, options?: RpcOptions): UnaryCall<UpdatePhotoRequest, CommonResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePhotoRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemovePhone(users.RemovePhoneRequest) returns (users.CommonResponse);
     */
    removePhone(input: RemovePhoneRequest, options?: RpcOptions): UnaryCall<RemovePhoneRequest, CommonResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemovePhoneRequest, CommonResponse>("unary", this._transport, method, opt, input);
    }
}
