// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "users/users.proto" (package "users", syntax proto3)
// tslint:disable
import { Response } from "../common/common";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message users.CommonRequest
 */
export interface CommonRequest {
    /**
     * @generated from protobuf field: uint32 accountId = 2;
     */
    accountId: number;
}
/**
 * @generated from protobuf message users.IdentifyRequest
 */
export interface IdentifyRequest {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
    /**
     * @generated from protobuf field: string userAgent = 2;
     */
    userAgent: string;
    /**
     * @generated from protobuf field: int32 device = 3;
     */
    device: number;
    /**
     * @generated from protobuf field: bytes ip = 4;
     */
    ip: Uint8Array;
    /**
     * @generated from protobuf field: string fcm = 5;
     */
    fcm: string;
}
/**
 * @generated from protobuf message users.IdentifyResponse
 */
export interface IdentifyResponse {
    /**
     * @generated from protobuf field: uint32 status = 1;
     */
    status: number;
    /**
     * @generated from protobuf field: optional users.AccountFull account = 2;
     */
    account?: AccountFull;
}
/**
 * @generated from protobuf message users.LoginRequest
 */
export interface LoginRequest {
    /**
     * @generated from protobuf field: string phone = 1;
     */
    phone: string;
}
/**
 * @generated from protobuf message users.LoginResponse
 */
export interface LoginResponse {
    /**
     * @generated from protobuf field: uint32 status = 1;
     */
    status: number;
    /**
     * @generated from protobuf field: uint32 type = 2;
     */
    type: number;
    /**
     * @generated from protobuf field: repeated uint32 methods = 3;
     */
    methods: number[];
    /**
     * @generated from protobuf field: string data = 4;
     */
    data: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp endedAt = 5;
     */
    endedAt?: Timestamp;
}
/**
 * @generated from protobuf message users.AccountFull
 */
export interface AccountFull {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string surname = 3;
     */
    surname: string;
    /**
     * @generated from protobuf field: string patronymic = 4;
     */
    patronymic: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp birthdate = 5;
     */
    birthdate?: Timestamp;
    /**
     * @generated from protobuf field: int32 country = 6;
     */
    country: number;
    /**
     * @generated from protobuf field: int32 district = 7;
     */
    district: number;
    /**
     * @generated from protobuf field: int32 locale = 8;
     */
    locale: number;
    /**
     * @generated from protobuf field: int32 timezone = 9;
     */
    timezone: number;
    /**
     * @generated from protobuf field: int32 photo = 10;
     */
    photo: number;
    /**
     * @generated from protobuf field: repeated users.AccountEmail emails = 11;
     */
    emails: AccountEmail[];
    /**
     * @generated from protobuf field: repeated users.AccountPhone phones = 12;
     */
    phones: AccountPhone[];
    /**
     * @generated from protobuf field: repeated users.AccountRole roles = 13;
     */
    roles: AccountRole[];
    /**
     * @generated from protobuf field: google.protobuf.Timestamp createdAt = 14;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updatedAt = 15;
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message users.CheckCodeRequest
 */
export interface CheckCodeRequest {
    /**
     * @generated from protobuf field: string code = 1;
     */
    code: string;
}
/**
 * @generated from protobuf message users.HasSessionRequest
 */
export interface HasSessionRequest {
    /**
     * @generated from protobuf field: int64 sessionId = 1;
     */
    sessionId: bigint;
    /**
     * @generated from protobuf field: uint32 accountId = 2;
     */
    accountId: number;
}
/**
 * @generated from protobuf message users.RegisterRequest
 */
export interface RegisterRequest {
    /**
     * @generated from protobuf field: string phone = 1;
     */
    phone: string;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string surname = 3;
     */
    surname: string;
    /**
     * @generated from protobuf field: int32 country = 10;
     */
    country: number;
    /**
     * @generated from protobuf field: int32 district = 11;
     */
    district: number;
    /**
     * @generated from protobuf field: int32 locale = 12;
     */
    locale: number;
    /**
     * @generated from protobuf field: int32 timezone = 13;
     */
    timezone: number;
}
// message LoginRequest {
//  string phone = 1;
// }
// 
// message LoginResponse {
//  uint32 status = 1;
//  optional int64 sessionId = 2;
//  optional Account account = 3;
// }

/**
 * @generated from protobuf message users.Account
 */
export interface Account {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: repeated users.AccountPhone phones = 2;
     */
    phones: AccountPhone[];
    /**
     * @generated from protobuf field: repeated users.AccountEmail emails = 3;
     */
    emails: AccountEmail[];
    /**
     * @generated from protobuf field: repeated users.AccountRole roles = 4;
     */
    roles: AccountRole[];
    /**
     * @generated from protobuf field: string photo = 5;
     */
    photo: string;
    /**
     * @generated from protobuf field: string name = 6;
     */
    name: string;
    /**
     * @generated from protobuf field: string surname = 7;
     */
    surname: string;
    /**
     * @generated from protobuf field: string patronymic = 8;
     */
    patronymic: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp birthdate = 9;
     */
    birthdate?: Timestamp;
    /**
     * @generated from protobuf field: int32 country = 10;
     */
    country: number;
    /**
     * @generated from protobuf field: int32 district = 11;
     */
    district: number;
    /**
     * @generated from protobuf field: int32 locale = 12;
     */
    locale: number;
    /**
     * @generated from protobuf field: int32 timezone = 13;
     */
    timezone: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 14;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 15;
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message users.AccountEmail
 */
export interface AccountEmail {
    /**
     * @generated from protobuf field: uint64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: uint32 account_id = 2;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string email = 3;
     */
    email: string;
    /**
     * @generated from protobuf field: int32 order = 4;
     */
    order: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 5;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 6;
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message users.AccountPhone
 */
export interface AccountPhone {
    /**
     * @generated from protobuf field: uint64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: uint32 account_id = 2;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string phone = 3;
     */
    phone: string;
    /**
     * @generated from protobuf field: int32 order = 4;
     */
    order: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 5;
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 6;
     */
    updatedAt?: Timestamp;
}
/**
 * @generated from protobuf message users.AccountRole
 */
export interface AccountRole {
    /**
     * @generated from protobuf field: uint64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: uint32 account_id = 2;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string role = 3;
     */
    role: string;
    /**
     * @generated from protobuf field: int32 order = 4;
     */
    order: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp created_at = 5;
     */
    createdAt?: Timestamp;
}
/**
 * @generated from protobuf message users.UpdateAccountDataRequest
 */
export interface UpdateAccountDataRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string surname = 2;
     */
    surname: string;
    /**
     * @generated from protobuf field: string patronymic = 3;
     */
    patronymic: string;
    /**
     * @generated from protobuf field: string birthdate = 4;
     */
    birthdate: string;
    /**
     * @generated from protobuf field: int32 country = 5;
     */
    country: number;
    /**
     * @generated from protobuf field: int32 district = 6;
     */
    district: number;
    /**
     * @generated from protobuf field: int32 locale = 7;
     */
    locale: number;
    /**
     * @generated from protobuf field: int32 timezone = 8;
     */
    timezone: number;
}
/**
 * @generated from protobuf message users.UpdatePasswordRequest
 */
export interface UpdatePasswordRequest {
    /**
     * @generated from protobuf field: int32 accountId = 1;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
}
/**
 * @generated from protobuf message users.UpdatePhotoRequest
 */
export interface UpdatePhotoRequest {
    /**
     * @generated from protobuf field: int32 accountId = 1;
     */
    accountId: number;
    /**
     * @generated from protobuf field: bytes photo = 2;
     */
    photo: Uint8Array;
}
/**
 * @generated from protobuf message users.AddPhoneRequest
 */
export interface AddPhoneRequest {
    /**
     * @generated from protobuf field: int32 accountId = 1;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string phone = 2;
     */
    phone: string;
}
/**
 * @generated from protobuf message users.UpdatePhoneRequest
 */
export interface UpdatePhoneRequest {
    /**
     * @generated from protobuf field: int32 accountId = 1;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string phone = 2;
     */
    phone: string;
}
/**
 * @generated from protobuf message users.RemovePhoneRequest
 */
export interface RemovePhoneRequest {
    /**
     * @generated from protobuf field: int32 accountId = 1;
     */
    accountId: number;
    /**
     * @generated from protobuf field: string phone = 2;
     */
    phone: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class CommonRequest$Type extends MessageType<CommonRequest> {
    constructor() {
        super("users.CommonRequest", [
            { no: 2, name: "accountId", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<CommonRequest>): CommonRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        if (value !== undefined)
            reflectionMergePartial<CommonRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommonRequest): CommonRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 accountId */ 2:
                    message.accountId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommonRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 accountId = 2; */
        if (message.accountId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.accountId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.CommonRequest
 */
export const CommonRequest = new CommonRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentifyRequest$Type extends MessageType<IdentifyRequest> {
    constructor() {
        super("users.IdentifyRequest", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "userAgent", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "device", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "ip", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 5, name: "fcm", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IdentifyRequest>): IdentifyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.token = "";
        message.userAgent = "";
        message.device = 0;
        message.ip = new Uint8Array(0);
        message.fcm = "";
        if (value !== undefined)
            reflectionMergePartial<IdentifyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentifyRequest): IdentifyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string token */ 1:
                    message.token = reader.string();
                    break;
                case /* string userAgent */ 2:
                    message.userAgent = reader.string();
                    break;
                case /* int32 device */ 3:
                    message.device = reader.int32();
                    break;
                case /* bytes ip */ 4:
                    message.ip = reader.bytes();
                    break;
                case /* string fcm */ 5:
                    message.fcm = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentifyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string token = 1; */
        if (message.token !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.token);
        /* string userAgent = 2; */
        if (message.userAgent !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.userAgent);
        /* int32 device = 3; */
        if (message.device !== 0)
            writer.tag(3, WireType.Varint).int32(message.device);
        /* bytes ip = 4; */
        if (message.ip.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.ip);
        /* string fcm = 5; */
        if (message.fcm !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.fcm);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.IdentifyRequest
 */
export const IdentifyRequest = new IdentifyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IdentifyResponse$Type extends MessageType<IdentifyResponse> {
    constructor() {
        super("users.IdentifyResponse", [
            { no: 1, name: "status", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "account", kind: "message", T: () => AccountFull }
        ]);
    }
    create(value?: PartialMessage<IdentifyResponse>): IdentifyResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<IdentifyResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IdentifyResponse): IdentifyResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 status */ 1:
                    message.status = reader.uint32();
                    break;
                case /* optional users.AccountFull account */ 2:
                    message.account = AccountFull.internalBinaryRead(reader, reader.uint32(), options, message.account);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IdentifyResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).uint32(message.status);
        /* optional users.AccountFull account = 2; */
        if (message.account)
            AccountFull.internalBinaryWrite(message.account, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.IdentifyResponse
 */
export const IdentifyResponse = new IdentifyResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LoginRequest$Type extends MessageType<LoginRequest> {
    constructor() {
        super("users.LoginRequest", [
            { no: 1, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LoginRequest>): LoginRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.phone = "";
        if (value !== undefined)
            reflectionMergePartial<LoginRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginRequest): LoginRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string phone */ 1:
                    message.phone = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string phone = 1; */
        if (message.phone !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.LoginRequest
 */
export const LoginRequest = new LoginRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LoginResponse$Type extends MessageType<LoginResponse> {
    constructor() {
        super("users.LoginResponse", [
            { no: 1, name: "status", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "type", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "methods", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "data", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "endedAt", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<LoginResponse>): LoginResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        message.type = 0;
        message.methods = [];
        message.data = "";
        if (value !== undefined)
            reflectionMergePartial<LoginResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LoginResponse): LoginResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 status */ 1:
                    message.status = reader.uint32();
                    break;
                case /* uint32 type */ 2:
                    message.type = reader.uint32();
                    break;
                case /* repeated uint32 methods */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.methods.push(reader.uint32());
                    else
                        message.methods.push(reader.uint32());
                    break;
                case /* string data */ 4:
                    message.data = reader.string();
                    break;
                case /* google.protobuf.Timestamp endedAt */ 5:
                    message.endedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LoginResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).uint32(message.status);
        /* uint32 type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).uint32(message.type);
        /* repeated uint32 methods = 3; */
        if (message.methods.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.methods.length; i++)
                writer.uint32(message.methods[i]);
            writer.join();
        }
        /* string data = 4; */
        if (message.data !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.data);
        /* google.protobuf.Timestamp endedAt = 5; */
        if (message.endedAt)
            Timestamp.internalBinaryWrite(message.endedAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.LoginResponse
 */
export const LoginResponse = new LoginResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AccountFull$Type extends MessageType<AccountFull> {
    constructor() {
        super("users.AccountFull", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "surname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "patronymic", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "birthdate", kind: "message", T: () => Timestamp },
            { no: 6, name: "country", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "district", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "locale", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "timezone", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "photo", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "emails", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AccountEmail },
            { no: 12, name: "phones", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AccountPhone },
            { no: 13, name: "roles", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AccountRole },
            { no: 14, name: "createdAt", kind: "message", T: () => Timestamp },
            { no: 15, name: "updatedAt", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<AccountFull>): AccountFull {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.name = "";
        message.surname = "";
        message.patronymic = "";
        message.country = 0;
        message.district = 0;
        message.locale = 0;
        message.timezone = 0;
        message.photo = 0;
        message.emails = [];
        message.phones = [];
        message.roles = [];
        if (value !== undefined)
            reflectionMergePartial<AccountFull>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AccountFull): AccountFull {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string surname */ 3:
                    message.surname = reader.string();
                    break;
                case /* string patronymic */ 4:
                    message.patronymic = reader.string();
                    break;
                case /* google.protobuf.Timestamp birthdate */ 5:
                    message.birthdate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.birthdate);
                    break;
                case /* int32 country */ 6:
                    message.country = reader.int32();
                    break;
                case /* int32 district */ 7:
                    message.district = reader.int32();
                    break;
                case /* int32 locale */ 8:
                    message.locale = reader.int32();
                    break;
                case /* int32 timezone */ 9:
                    message.timezone = reader.int32();
                    break;
                case /* int32 photo */ 10:
                    message.photo = reader.int32();
                    break;
                case /* repeated users.AccountEmail emails */ 11:
                    message.emails.push(AccountEmail.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated users.AccountPhone phones */ 12:
                    message.phones.push(AccountPhone.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated users.AccountRole roles */ 13:
                    message.roles.push(AccountRole.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* google.protobuf.Timestamp createdAt */ 14:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updatedAt */ 15:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AccountFull, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string surname = 3; */
        if (message.surname !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.surname);
        /* string patronymic = 4; */
        if (message.patronymic !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.patronymic);
        /* google.protobuf.Timestamp birthdate = 5; */
        if (message.birthdate)
            Timestamp.internalBinaryWrite(message.birthdate, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* int32 country = 6; */
        if (message.country !== 0)
            writer.tag(6, WireType.Varint).int32(message.country);
        /* int32 district = 7; */
        if (message.district !== 0)
            writer.tag(7, WireType.Varint).int32(message.district);
        /* int32 locale = 8; */
        if (message.locale !== 0)
            writer.tag(8, WireType.Varint).int32(message.locale);
        /* int32 timezone = 9; */
        if (message.timezone !== 0)
            writer.tag(9, WireType.Varint).int32(message.timezone);
        /* int32 photo = 10; */
        if (message.photo !== 0)
            writer.tag(10, WireType.Varint).int32(message.photo);
        /* repeated users.AccountEmail emails = 11; */
        for (let i = 0; i < message.emails.length; i++)
            AccountEmail.internalBinaryWrite(message.emails[i], writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* repeated users.AccountPhone phones = 12; */
        for (let i = 0; i < message.phones.length; i++)
            AccountPhone.internalBinaryWrite(message.phones[i], writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* repeated users.AccountRole roles = 13; */
        for (let i = 0; i < message.roles.length; i++)
            AccountRole.internalBinaryWrite(message.roles[i], writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp createdAt = 14; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updatedAt = 15; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.AccountFull
 */
export const AccountFull = new AccountFull$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckCodeRequest$Type extends MessageType<CheckCodeRequest> {
    constructor() {
        super("users.CheckCodeRequest", [
            { no: 1, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CheckCodeRequest>): CheckCodeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.code = "";
        if (value !== undefined)
            reflectionMergePartial<CheckCodeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckCodeRequest): CheckCodeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string code */ 1:
                    message.code = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckCodeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string code = 1; */
        if (message.code !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.code);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.CheckCodeRequest
 */
export const CheckCodeRequest = new CheckCodeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HasSessionRequest$Type extends MessageType<HasSessionRequest> {
    constructor() {
        super("users.HasSessionRequest", [
            { no: 1, name: "sessionId", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "accountId", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<HasSessionRequest>): HasSessionRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sessionId = 0n;
        message.accountId = 0;
        if (value !== undefined)
            reflectionMergePartial<HasSessionRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HasSessionRequest): HasSessionRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 sessionId */ 1:
                    message.sessionId = reader.int64().toBigInt();
                    break;
                case /* uint32 accountId */ 2:
                    message.accountId = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: HasSessionRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 sessionId = 1; */
        if (message.sessionId !== 0n)
            writer.tag(1, WireType.Varint).int64(message.sessionId);
        /* uint32 accountId = 2; */
        if (message.accountId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.accountId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.HasSessionRequest
 */
export const HasSessionRequest = new HasSessionRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterRequest$Type extends MessageType<RegisterRequest> {
    constructor() {
        super("users.RegisterRequest", [
            { no: 1, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "surname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "country", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "district", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "locale", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "timezone", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterRequest>): RegisterRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.phone = "";
        message.name = "";
        message.surname = "";
        message.country = 0;
        message.district = 0;
        message.locale = 0;
        message.timezone = 0;
        if (value !== undefined)
            reflectionMergePartial<RegisterRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterRequest): RegisterRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string phone */ 1:
                    message.phone = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string surname */ 3:
                    message.surname = reader.string();
                    break;
                case /* int32 country */ 10:
                    message.country = reader.int32();
                    break;
                case /* int32 district */ 11:
                    message.district = reader.int32();
                    break;
                case /* int32 locale */ 12:
                    message.locale = reader.int32();
                    break;
                case /* int32 timezone */ 13:
                    message.timezone = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string phone = 1; */
        if (message.phone !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.phone);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string surname = 3; */
        if (message.surname !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.surname);
        /* int32 country = 10; */
        if (message.country !== 0)
            writer.tag(10, WireType.Varint).int32(message.country);
        /* int32 district = 11; */
        if (message.district !== 0)
            writer.tag(11, WireType.Varint).int32(message.district);
        /* int32 locale = 12; */
        if (message.locale !== 0)
            writer.tag(12, WireType.Varint).int32(message.locale);
        /* int32 timezone = 13; */
        if (message.timezone !== 0)
            writer.tag(13, WireType.Varint).int32(message.timezone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.RegisterRequest
 */
export const RegisterRequest = new RegisterRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Account$Type extends MessageType<Account> {
    constructor() {
        super("users.Account", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "phones", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AccountPhone },
            { no: 3, name: "emails", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AccountEmail },
            { no: 4, name: "roles", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => AccountRole },
            { no: 5, name: "photo", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "surname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "patronymic", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "birthdate", kind: "message", T: () => Timestamp },
            { no: 10, name: "country", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "district", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "locale", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "timezone", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 14, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 15, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Account>): Account {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0;
        message.phones = [];
        message.emails = [];
        message.roles = [];
        message.photo = "";
        message.name = "";
        message.surname = "";
        message.patronymic = "";
        message.country = 0;
        message.district = 0;
        message.locale = 0;
        message.timezone = 0;
        if (value !== undefined)
            reflectionMergePartial<Account>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Account): Account {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* repeated users.AccountPhone phones */ 2:
                    message.phones.push(AccountPhone.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated users.AccountEmail emails */ 3:
                    message.emails.push(AccountEmail.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated users.AccountRole roles */ 4:
                    message.roles.push(AccountRole.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string photo */ 5:
                    message.photo = reader.string();
                    break;
                case /* string name */ 6:
                    message.name = reader.string();
                    break;
                case /* string surname */ 7:
                    message.surname = reader.string();
                    break;
                case /* string patronymic */ 8:
                    message.patronymic = reader.string();
                    break;
                case /* google.protobuf.Timestamp birthdate */ 9:
                    message.birthdate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.birthdate);
                    break;
                case /* int32 country */ 10:
                    message.country = reader.int32();
                    break;
                case /* int32 district */ 11:
                    message.district = reader.int32();
                    break;
                case /* int32 locale */ 12:
                    message.locale = reader.int32();
                    break;
                case /* int32 timezone */ 13:
                    message.timezone = reader.int32();
                    break;
                case /* google.protobuf.Timestamp created_at */ 14:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 15:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Account, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* repeated users.AccountPhone phones = 2; */
        for (let i = 0; i < message.phones.length; i++)
            AccountPhone.internalBinaryWrite(message.phones[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated users.AccountEmail emails = 3; */
        for (let i = 0; i < message.emails.length; i++)
            AccountEmail.internalBinaryWrite(message.emails[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated users.AccountRole roles = 4; */
        for (let i = 0; i < message.roles.length; i++)
            AccountRole.internalBinaryWrite(message.roles[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string photo = 5; */
        if (message.photo !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.photo);
        /* string name = 6; */
        if (message.name !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.name);
        /* string surname = 7; */
        if (message.surname !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.surname);
        /* string patronymic = 8; */
        if (message.patronymic !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.patronymic);
        /* google.protobuf.Timestamp birthdate = 9; */
        if (message.birthdate)
            Timestamp.internalBinaryWrite(message.birthdate, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* int32 country = 10; */
        if (message.country !== 0)
            writer.tag(10, WireType.Varint).int32(message.country);
        /* int32 district = 11; */
        if (message.district !== 0)
            writer.tag(11, WireType.Varint).int32(message.district);
        /* int32 locale = 12; */
        if (message.locale !== 0)
            writer.tag(12, WireType.Varint).int32(message.locale);
        /* int32 timezone = 13; */
        if (message.timezone !== 0)
            writer.tag(13, WireType.Varint).int32(message.timezone);
        /* google.protobuf.Timestamp created_at = 14; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 15; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.Account
 */
export const Account = new Account$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AccountEmail$Type extends MessageType<AccountEmail> {
    constructor() {
        super("users.AccountEmail", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "account_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<AccountEmail>): AccountEmail {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.accountId = 0;
        message.email = "";
        message.order = 0;
        if (value !== undefined)
            reflectionMergePartial<AccountEmail>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AccountEmail): AccountEmail {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toBigInt();
                    break;
                case /* uint32 account_id */ 2:
                    message.accountId = reader.uint32();
                    break;
                case /* string email */ 3:
                    message.email = reader.string();
                    break;
                case /* int32 order */ 4:
                    message.order = reader.int32();
                    break;
                case /* google.protobuf.Timestamp created_at */ 5:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 6:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AccountEmail, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* uint32 account_id = 2; */
        if (message.accountId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.accountId);
        /* string email = 3; */
        if (message.email !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.email);
        /* int32 order = 4; */
        if (message.order !== 0)
            writer.tag(4, WireType.Varint).int32(message.order);
        /* google.protobuf.Timestamp created_at = 5; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 6; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.AccountEmail
 */
export const AccountEmail = new AccountEmail$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AccountPhone$Type extends MessageType<AccountPhone> {
    constructor() {
        super("users.AccountPhone", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "account_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "created_at", kind: "message", T: () => Timestamp },
            { no: 6, name: "updated_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<AccountPhone>): AccountPhone {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.accountId = 0;
        message.phone = "";
        message.order = 0;
        if (value !== undefined)
            reflectionMergePartial<AccountPhone>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AccountPhone): AccountPhone {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toBigInt();
                    break;
                case /* uint32 account_id */ 2:
                    message.accountId = reader.uint32();
                    break;
                case /* string phone */ 3:
                    message.phone = reader.string();
                    break;
                case /* int32 order */ 4:
                    message.order = reader.int32();
                    break;
                case /* google.protobuf.Timestamp created_at */ 5:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 6:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AccountPhone, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* uint32 account_id = 2; */
        if (message.accountId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.accountId);
        /* string phone = 3; */
        if (message.phone !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.phone);
        /* int32 order = 4; */
        if (message.order !== 0)
            writer.tag(4, WireType.Varint).int32(message.order);
        /* google.protobuf.Timestamp created_at = 5; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 6; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.AccountPhone
 */
export const AccountPhone = new AccountPhone$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AccountRole$Type extends MessageType<AccountRole> {
    constructor() {
        super("users.AccountRole", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "account_id", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "order", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "created_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<AccountRole>): AccountRole {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.accountId = 0;
        message.role = "";
        message.order = 0;
        if (value !== undefined)
            reflectionMergePartial<AccountRole>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AccountRole): AccountRole {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toBigInt();
                    break;
                case /* uint32 account_id */ 2:
                    message.accountId = reader.uint32();
                    break;
                case /* string role */ 3:
                    message.role = reader.string();
                    break;
                case /* int32 order */ 4:
                    message.order = reader.int32();
                    break;
                case /* google.protobuf.Timestamp created_at */ 5:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AccountRole, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* uint32 account_id = 2; */
        if (message.accountId !== 0)
            writer.tag(2, WireType.Varint).uint32(message.accountId);
        /* string role = 3; */
        if (message.role !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.role);
        /* int32 order = 4; */
        if (message.order !== 0)
            writer.tag(4, WireType.Varint).int32(message.order);
        /* google.protobuf.Timestamp created_at = 5; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.AccountRole
 */
export const AccountRole = new AccountRole$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateAccountDataRequest$Type extends MessageType<UpdateAccountDataRequest> {
    constructor() {
        super("users.UpdateAccountDataRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "surname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "patronymic", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "birthdate", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "country", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "district", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "locale", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "timezone", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateAccountDataRequest>): UpdateAccountDataRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.surname = "";
        message.patronymic = "";
        message.birthdate = "";
        message.country = 0;
        message.district = 0;
        message.locale = 0;
        message.timezone = 0;
        if (value !== undefined)
            reflectionMergePartial<UpdateAccountDataRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateAccountDataRequest): UpdateAccountDataRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string surname */ 2:
                    message.surname = reader.string();
                    break;
                case /* string patronymic */ 3:
                    message.patronymic = reader.string();
                    break;
                case /* string birthdate */ 4:
                    message.birthdate = reader.string();
                    break;
                case /* int32 country */ 5:
                    message.country = reader.int32();
                    break;
                case /* int32 district */ 6:
                    message.district = reader.int32();
                    break;
                case /* int32 locale */ 7:
                    message.locale = reader.int32();
                    break;
                case /* int32 timezone */ 8:
                    message.timezone = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateAccountDataRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string surname = 2; */
        if (message.surname !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.surname);
        /* string patronymic = 3; */
        if (message.patronymic !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.patronymic);
        /* string birthdate = 4; */
        if (message.birthdate !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.birthdate);
        /* int32 country = 5; */
        if (message.country !== 0)
            writer.tag(5, WireType.Varint).int32(message.country);
        /* int32 district = 6; */
        if (message.district !== 0)
            writer.tag(6, WireType.Varint).int32(message.district);
        /* int32 locale = 7; */
        if (message.locale !== 0)
            writer.tag(7, WireType.Varint).int32(message.locale);
        /* int32 timezone = 8; */
        if (message.timezone !== 0)
            writer.tag(8, WireType.Varint).int32(message.timezone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.UpdateAccountDataRequest
 */
export const UpdateAccountDataRequest = new UpdateAccountDataRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePasswordRequest$Type extends MessageType<UpdatePasswordRequest> {
    constructor() {
        super("users.UpdatePasswordRequest", [
            { no: 1, name: "accountId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdatePasswordRequest>): UpdatePasswordRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.password = "";
        if (value !== undefined)
            reflectionMergePartial<UpdatePasswordRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePasswordRequest): UpdatePasswordRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 accountId */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* string password */ 2:
                    message.password = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePasswordRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 accountId = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* string password = 2; */
        if (message.password !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.password);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.UpdatePasswordRequest
 */
export const UpdatePasswordRequest = new UpdatePasswordRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePhotoRequest$Type extends MessageType<UpdatePhotoRequest> {
    constructor() {
        super("users.UpdatePhotoRequest", [
            { no: 1, name: "accountId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "photo", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<UpdatePhotoRequest>): UpdatePhotoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.photo = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<UpdatePhotoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePhotoRequest): UpdatePhotoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 accountId */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* bytes photo */ 2:
                    message.photo = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePhotoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 accountId = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* bytes photo = 2; */
        if (message.photo.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.photo);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.UpdatePhotoRequest
 */
export const UpdatePhotoRequest = new UpdatePhotoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddPhoneRequest$Type extends MessageType<AddPhoneRequest> {
    constructor() {
        super("users.AddPhoneRequest", [
            { no: 1, name: "accountId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddPhoneRequest>): AddPhoneRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.phone = "";
        if (value !== undefined)
            reflectionMergePartial<AddPhoneRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddPhoneRequest): AddPhoneRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 accountId */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* string phone */ 2:
                    message.phone = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddPhoneRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 accountId = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* string phone = 2; */
        if (message.phone !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.AddPhoneRequest
 */
export const AddPhoneRequest = new AddPhoneRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdatePhoneRequest$Type extends MessageType<UpdatePhoneRequest> {
    constructor() {
        super("users.UpdatePhoneRequest", [
            { no: 1, name: "accountId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdatePhoneRequest>): UpdatePhoneRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.phone = "";
        if (value !== undefined)
            reflectionMergePartial<UpdatePhoneRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdatePhoneRequest): UpdatePhoneRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 accountId */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* string phone */ 2:
                    message.phone = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdatePhoneRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 accountId = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* string phone = 2; */
        if (message.phone !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.UpdatePhoneRequest
 */
export const UpdatePhoneRequest = new UpdatePhoneRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemovePhoneRequest$Type extends MessageType<RemovePhoneRequest> {
    constructor() {
        super("users.RemovePhoneRequest", [
            { no: 1, name: "accountId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "phone", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RemovePhoneRequest>): RemovePhoneRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accountId = 0;
        message.phone = "";
        if (value !== undefined)
            reflectionMergePartial<RemovePhoneRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemovePhoneRequest): RemovePhoneRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 accountId */ 1:
                    message.accountId = reader.int32();
                    break;
                case /* string phone */ 2:
                    message.phone = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemovePhoneRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 accountId = 1; */
        if (message.accountId !== 0)
            writer.tag(1, WireType.Varint).int32(message.accountId);
        /* string phone = 2; */
        if (message.phone !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.phone);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message users.RemovePhoneRequest
 */
export const RemovePhoneRequest = new RemovePhoneRequest$Type();
/**
 * @generated ServiceType for protobuf service users.Users
 */
export const Users = new ServiceType("users.Users", [
    { name: "Identify", options: {}, I: IdentifyRequest, O: IdentifyResponse },
    { name: "Login", options: {}, I: LoginRequest, O: LoginResponse },
    { name: "CheckCode", options: {}, I: CheckCodeRequest, O: Response },
    { name: "LoginByCode", options: {}, I: LoginRequest, O: LoginResponse },
    { name: "Register", options: {}, I: RegisterRequest, O: LoginResponse },
    { name: "HasSession", options: {}, I: HasSessionRequest, O: Response },
    { name: "GetAccount", options: {}, I: CommonRequest, O: Account },
    { name: "UpdateAccountData", options: {}, I: UpdateAccountDataRequest, O: Response },
    { name: "UpdatePassword", options: {}, I: UpdatePasswordRequest, O: Response },
    { name: "UpdatePhoto", options: {}, I: UpdatePhotoRequest, O: Response },
    { name: "AddPhone", options: {}, I: AddPhoneRequest, O: Response },
    { name: "UpdatePhone", options: {}, I: UpdatePhotoRequest, O: Response },
    { name: "RemovePhone", options: {}, I: RemovePhoneRequest, O: Response }
]);
